### ISSUE TITLE
Error `.text' will not fit in region `iram1_0_seg'

### ISSUE THREAD

**Issue by archont94** [con-f-use/esp82XX-basic#1]
Hi,
I run this project without problems on Linux Mint, but swiching between Mint and Windows is killing me. So I decide to run all enviroment on Cygwin. I succesfully build esp-open-sdk and I add proper ESP_ROOT to my bash.rc. During execution of `make all` I get error:

```
/cygdrive/c/cygwin64/home/Archont/esp2866/esp-open-sdk/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: image.elf section `.text' will not fit in region `iram1_0_seg'
/cygdrive/c/cygwin64/home/Archont/esp2866/esp-open-sdk/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: region `iram1_0_seg' overflowed by 224 bytes
```

I don't make any changes in code, so this isn't problem. Do you have any idea how to fix this? Maybe @cnlohr can help :).

**Comment by archont94** [comment]
OK, nevermind - this is very similar situation as mention here:
https://github.com/cnlohr/esp82xx/issues/34

To fix that issue I changed in esp-open-sdk main Makefile `VENDOR_SDK = 2.0.0` to`VENDOR_SDK = 1.5.2` and recompile SDK.

**Comment by con-f-use** [comment]
The linked [installation script](https://gist.github.com/con-f-use/d086ca941c2c80fbde6d8996b8a50761) (I assume you're using that, but your issue doesn't actually specify) for the SKD should have changed `VENDOR_SDK` to `1.5.2` automatically. I suspect, your grep/sed don't work properly on cygwin.

Here is the respective line:

```
sed -i 's/^\(\s*VENDOR_SDK\s*=\s*\).*$/\1 1.5.2/' Makefile   # Old version of sdk (v1.5.2) before espressif filled the iram
```
